# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"%\n\x0e\x41\x64\x64TaskRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x1d\n\x0f\x41\x64\x64TaskResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x0fGetTaskResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"9\n\x11ListTasksResponse\x12$\n\x05tasks\x18\x01 \x03(\x0b\x32\x15.todo.GetTaskResponse2\xb0\x01\n\x0bTodoService\x12\x36\n\x07\x41\x64\x64Task\x12\x14.todo.AddTaskRequest\x1a\x15.todo.AddTaskResponse\x12\x36\n\x07GetTask\x12\x14.todo.GetTaskRequest\x1a\x15.todo.GetTaskResponse\x12\x31\n\tListTasks\x12\x0b.todo.Empty\x1a\x17.todo.ListTasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTASKREQUEST']._serialized_start=20
  _globals['_ADDTASKREQUEST']._serialized_end=57
  _globals['_ADDTASKRESPONSE']._serialized_start=59
  _globals['_ADDTASKRESPONSE']._serialized_end=88
  _globals['_GETTASKREQUEST']._serialized_start=90
  _globals['_GETTASKREQUEST']._serialized_end=118
  _globals['_GETTASKRESPONSE']._serialized_start=120
  _globals['_GETTASKRESPONSE']._serialized_end=170
  _globals['_EMPTY']._serialized_start=172
  _globals['_EMPTY']._serialized_end=179
  _globals['_LISTTASKSRESPONSE']._serialized_start=181
  _globals['_LISTTASKSRESPONSE']._serialized_end=238
  _globals['_TODOSERVICE']._serialized_start=241
  _globals['_TODOSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
